const ACTIVE_ORDER = "activa";
const DONE_ORDER = "terminada";
const DELIVERED_ORDER = "enviada";
const PRINTER_1 = "t3";
const PRINTER_2 = "t4";
const ORDER_MODE_DOMICILIO = "domicilio";
const CAJA_PRINCIPAL = "principal";

module.exports = {
  ACTIVE_ORDER: ACTIVE_ORDER,
  DONE_ORDER: DONE_ORDER,
  DELIVERED_ORDER: DELIVERED_ORDER,
  PRINTER_1: PRINTER_1,
  PRINTER_2: PRINTER_2,
  ORDER_MODE_DOMICILIO: ORDER_MODE_DOMICILIO,
  CAJA_PRINCIPAL: CAJA_PRINCIPAL,
};
